### ISSUE TITLE
Stopped rendering too early

### ISSUE THREAD

**Issue by djc** [filllabs/dependi#46] opened 2024-07-22 08:25 UTC
**Describe the bug**

Congrats on starting a company around this extension, I hope it works out for you!

It seems there are some cases where Dependi stops rerendering too early. I used to saw this temporarily with the crates extension too but I think it used to ~always recover to a correct state in the end.

**To Reproduce**

1. Type a new dependency in `Cargo.toml`
2. Wait for a few seconds

**Expected behavior**

It's not a big issue to temporarily render the annotation in the middle of the line for a bit, but it should recover when I'm done typing.

**Screenshots**

<img width="246" alt="Screenshot 2024-07-22 at 10 22 27" src="https://github.com/user-attachments/assets/23602e10-6313-412c-8d36-4113be5814ca">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 0.7.4

**Comment by serayuzgur** [comment] 2024-07-22 10:24
First of all, thank you for your kindness. We will look into it. We may ask you further questions then.

**Comment by djc** [comment] 2024-07-29 08:42
Why is this getting closed?

**Comment by MOzanGul** [comment] 2024-07-29 08:53
We closed this issue after failing to reproduce the bug. If you still experience this issue we can try to reproduce this bug furthermore.

**Comment by MOzanGul** [comment] 2024-07-29 09:03
Also if you could provide

**Comment by MOzanGul** [comment] 2024-08-01 08:44
Hi @djc, we couldn't reproduce this bug since Dependi shouldn't work with new dependencies if the manifest file (cargo.toml in this case) is not saved. If decorations are still buggy after saving your file please inform us.

**Comment by djc** [comment] 2024-08-01 13:19
Okay, if you aren't able to reproduce this it's okay to close this. What I don't like is closing it without any further comment after I've spent some effort writing up an issue that I observed.

**Comment by MOzanGul** [comment] 2024-08-01 13:32
It was a mistake on my behalf not communicating it clearly and it won't happen again. Thank you for your effort.

**Comment by MOzanGul** [comment] 2024-08-19 13:30
We are still not able to reproduce this bug so we are closing this issue for now.

**Closed by MOzanGul** 2024-08-19 13:30 UTC
Labels: bug

**Comment by djc** [comment] 2024-08-19 13:34
I did see this again today, so it is still there. However, I haven't found a reliable reproduction path.
