### ISSUE TITLE
Cannot display which dependency is no longer up-to-date

### ISSUE THREAD

**Issue by AurevoirXavier** [filllabs/dependi#15] opened 2024-07-17 03:15 UTC
<img width="833" alt="image" src="https://github.com/user-attachments/assets/4eba13a3-eb02-42ce-9b1e-58c1733c5ee0">

crates will notify me of a new version, but dependi will not.

**Comment by serayuzgur** [comment] 2024-07-17 05:51
Hi @AurevoirXavier  thanks for reaching. We will check it.

**Comment by MOzanGul** [comment] 2024-08-01 07:51
Hi @AurevoirXavier, we couldn't reproduce this bug. We would like to get more information about this issue you're having. Happy coding!

**Comment by doraemonkeys** [comment] 2024-08-02 10:37
Same here.  

Dependi v0.7.6
![image](https://github.com/user-attachments/assets/00e9f593-19d3-4f8f-8972-b22848ac510a)

**Comment by JoshLambda** [comment] 2024-08-04 01:28
Maybe a duplicate of #74 ? (already fixed on main branch)

**Comment by MOzanGul** [comment] 2024-08-08 10:12
Hi @AurevoirXavier , we have fixed this issue per your request in our new version 0.7.7.
We'd be really happy if you could review Dependi, here is our [reviews page](https://marketplace.visualstudio.com/items?itemName=fill-labs.dependi&ssr=false#review-details).

**Comment by AurevoirXavier** [comment] 2024-08-16 05:53
![image](https://github.com/user-attachments/assets/9c83de3b-4247-41c6-bff1-d1e359a77d0b)

It seems it only checks the lock file.

ndarray is outdated in lock. windows-capture is outdated in toml but not in the lock.

**Comment by MOzanGul** [comment] 2024-08-19 13:53
Hi @AurevoirXavier , can you please check this with newest version and please inform us if it still happens?

**Comment by MOzanGul** [comment] 2024-10-28 10:27
We're closing this issue since we couldn't reproduce the issue and couldn't get any information from the Issue owner.

**Closed by MOzanGul** 2024-10-28 10:27 UTC
Labels: bug
